OUTPUT=./bin/dbcli

build:
	@echo "building the cli..."
	@go build -o $(OUTPUT)

run-parse:
	@echo "running the parser..."
	@go run ../parser/main.go
query-one:
	@echo "finding the successor of the given node"
	@$(OUTPUT) one -f="/c/en/steam_locomotive"
query-two:
	@echo "finding the successor of the given node"
	@$(OUTPUT) two

query-three:
	@echo "finding the successor of the given node"
	@$(OUTPUT) three

query-four:
	@echo "finding the successor of the given node"
	@$(OUTPUT) four

query-five:
	@echo "finding the successor of the given node"
	@$(OUTPUT) five

query-six:
	@echo "finding the successor of the given node"
	@$(OUTPUT) six

query-seven:
	@echo "finding the successor of the given node"
	@$(OUTPUT) seven

query-eight:
	@echo "finding the successor of the given node"
	@$(OUTPUT) eight

query-nine:
	@echo "finding the successor of the given node"
	@$(OUTPUT) nine

query-ten:
	@echo "finding the successor of the given node"
	@$(OUTPUT) ten

query-eleven:
	@echo "finding the successor of the given node"
	@$(OUTPUT) eleven

query-twelve:
	@echo "finding the successor of the given node"
	@$(OUTPUT) twelve

query-thirteen:
	@echo "finding the successor of the given node"
	@$(OUTPUT) thirteen

query-fourteen:
	@echo "finding the successor of the given node"
	@$(OUTPUT) fourteen

query-fifteen:
	@echo "finding the successor of the given node"
	@$(OUTPUT) fifteen

query-sixteen:
	@echo "finding the successor of the given node"
	@$(OUTPUT) sixteen

query-seventeen:
	@echo "finding the successor of the given node"
	@$(OUTPUT) seventeen

query-eighteen:
	@echo "finding the successor of the given node"
	@$(OUTPUT) eighteen
